public enum isupss7_optional
{
  NONE = -1,
  CALLING_PARTY_NUMBER = 10,
  ORIGINAL_CALLED_NUMBER = 40,
  PROPAGATION_DELAY_COUNTER = 49,
  GENERIC_DIGITS = 193,
  JURISDICTION_INFORMATION = 196,
  GENERIC_NAME = 199,
  ORIGINATING_LINE_INFORMATION = 234,
  CHARGE_NUMBER = 235
}
